apiVersion: v1
kind: Service
metadata:
  namespace: session-dev
  name: redis-envoy-common
  labels:
    app: redis-envoy-common
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-cache
    - port: 6380
      targetPort: 6380
      name: envoy
  selector:
    component: redis-envoy