apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: session-dev

bases:
- ../../../../base/redis/cache-001/dynomitedb

patchesStrategicMerge:
- deployment.yaml
- service.yaml
- multiple-service.yaml

configMapGenerator:
- name: redis-config
  files:
  - redis.conf
- name: dyno-config-001
  files:
  - dynomite.yaml
  
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
