apiVersion: v1
kind: Service
metadata:
  namespace: session-dev
  name: redis-envoy-001
  labels:
    app: redis-envoy-001
spec:
  # type: LoadBalancer
  # loadBalancerIP: 192.168.0.79
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-envoy-001