apiVersion: v1
kind: Service
metadata:
  namespace: session-dev
  name: redis-dyno-common
  labels:
    app: redis-dyno-common
spec:
  # type: LoadBalancer
  # loadBalancerIP: 192.168.0.79
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    #app: redis-cache
    component: redis-dyno