server:
  port: 8080
  servlet:
    context-path: /emp-spring

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  config:
    import: 
    - file:./config/application-mariadb.yml
  application:
    name: emp-spring
  data:
    rest:
      basePath: /api

logging:
  level:
    '[com.htdp1.empspring]': debug
