apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: session-dev

bases:
- ../../../base/spring/emp-spring

patchesStrategicMerge:
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: emp-spring
  files:
  - application.yml
  - application-mariadb.yml
  
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
