apiVersion: v1
kind: Service
metadata:
  namespace: session-dev
  name: redis-common
  labels:
    app: redis-common
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-cache
  selector:
    component: redis