apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: session-dev

bases:
- ../../../base/redis/cache-002

patchesStrategicMerge:
- deployment.yaml
- service.yaml


configMapGenerator:
- name: redis-cache-002
  # behavior: replace
  files:
  - envoy.yaml
  
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
