apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: session-dev

bases:
- ../../../base/redis/cache-002

patchesStrategicMerge:
- deployment.yaml
- service.yaml


configMapGenerator:
- name: redis-cache-002
  files:
  - redis.conf
#- name: redis-cache-002-envoy
#  files:
#  - envoy.yaml
#- name: redis-cache-002-predixy
#  files:
#  - predixy/predixy.conf
#  - predixy/standalone.conf
#  - predixy/command.conf
#- name: redis-cache-002-dyno
#  files:
#  - dynomitedb/dynomite.yaml
#  - dynomitedb/dynomite.pem
  
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
