apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: session-dev

bases:
- ../../../base/redis/cache-aof

patchesStrategicMerge:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: redis-cache-aof
  # behavior: replace
  files:
  - redis.conf
  
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
