apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: session-dev
  name: redis-cache-aof
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
