apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-spring
  labels:
    app: session-spring
spec:
  replicas: 1
  # selector:
  #   matchLabels:
  #     app: session-spring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: session-spring
    spec:
      containers:
      - name: session-spring
        image: htdp1/session-spring:v3
        env:
        - name: spring.profiles.active
          value: dev
        - name: APPLICATION_NAME
          valueFrom: 
            configMapKeyRef:  
              name: session-spring
              key: appname
        - name: REDIS_HOST
          valueFrom: 
            configMapKeyRef:  
              name: session-spring
              key: host
        - name: REDIS_PORT
          valueFrom: 
            configMapKeyRef:  
              name: session-spring
              key: port
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: tomcat
          initialDelaySeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: tomcat
          initialDelaySeconds: 30
          periodSeconds: 5
      #   volumeMounts:
      #   - name: application-property
      #     mountPath: /config
      # volumes:
      # - name: application-property
      #   configMap:
      #   # Provide the name of the ConfigMap containing the files you want
      #   # to add to the container
      #     name: datasource
