apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: session-dev

bases:
- ../../base/spring

patchesStrategicMerge:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml

configMapGenerator:
- name: session-spring
  behavior: replace
  files:
  - application.yml
