apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: session-dev
  name: predixy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 4Gi
