apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-world
  labels:
    app: mariadb-world
spec:
  replicas: 1
  # selector:
  #   matchLabels:
  #     app: mariadb-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mariadb-world
    spec:
      containers:
      - name: mariadb-world
        image: htdp1/mariadb-world:latest
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 512Mi
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: skcc
