apiVersion: v1
kind: Service
metadata:
  namespace: session-dev
  name: redis-envoy
  labels:
    app: redis-envoy
spec:
  ports:
    - port: 6380
      targetPort: 6380
      name: redis
    - port: 8001
      targetPort: 8001
      name: admin
  selector:
    app: redis-envoy