apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: session-dev

bases:
- ../../../base/spring/session-spring

patchesStrategicMerge:
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: session-spring
  # behavior: replace
  files:
  - application.yml
  - application-redis.yml
  - application-apis.yml
  
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
