apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-mariadb
  labels:
    app: session-mariadb
spec:
  replicas: 1
  # selector:
  #   matchLabels:
  #     app: session-mariadb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: session-mariadb
    spec:
      containers:
      - name: session-mariadb
        image: mariadb:latest
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 1000m
            memory: 512Mi
