apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ngrinder-agent
  namespace: session-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 2Gi
