apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: session-dev
  name: ngrinder-agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
