apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrinder-controller
spec:
  selector:
    matchLabels:
      app: ngrinder-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ngrinder-controller
    spec:
      containers:
      - image: ngrinder/controller:latest
        name: ngrinder-controller
        ports:
        - containerPort: 80
        - containerPort: 16001
        - containerPort: 12000
        - containerPort: 12001
        - containerPort: 12002
        - containerPort: 12003
        - containerPort: 12004
        - containerPort: 12005
        - containerPort: 12006
        - containerPort: 12007
        - containerPort: 12008
        - containerPort: 12009
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1600m
            memory: 1024Mi
          requests:
            cpu: 800m
            memory: 512Mi
      hostAliases:
      - ip: "52.79.81.6"
        hostnames:
        - "k8s-sessiond-sessions-3ae919bacd-1173638282.ap-northeast-2.elb.amazonaws.com"
      - ip: "13.124.186.175"
        hostnames:
        - "k8s-sessiond-empsprin-eddc7b7a44-95816314.ap-northeast-2.elb.amazonaws.com"