server:
  port: 8080
  servlet:
    context-path: /dept-spring-always

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  config:
    import: 
    - file:./config/application-apis.yml
    - file:./config/application-redis.yml
    - file:./config/application-mariadb.yml
  application:
    name: dept-spring
  data:
    rest:
      basePath: /api

logging:
  level:
    root: warn                            # all logging
    '[com.htdp1.deptspring]': debug       # Application logging
    '[org.springframework.cache]': trace  # @Cacheable logging
    '[org.springframework.data]': trace   # JPA logging
    '[org.hibernate.SQL]': debug          # print JPA SQL 
    '[org.hibernate.type.descriptor.sql.BasicBinder]': trace # pring JPA SQL Parameters

### user defined ###
session:
  enabled: false

