spring: 
  session:
    store-type: redis
    redis:
      namespace: "htdp1:session"
      host: redis-session.session-dev
      port: 6379
      password: 

  cache: 
    type: redis
    redis:
      namespace: "htdp1:cache:"
      ttl: 10 # min
      host: redis-cache-always.session-dev
      port: 6379
      password:
      
  repository: 
    type: redis
    redis:
      namespace: ""
      host: redis-cache-always.session-dev
      port: 6379
      password:
